name: Execute FPI proofs minimal
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run proofs
        run: python3 run_proofs.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fpi-proofs
          path: |
            FPI_proofs_executed_byCI.ipynb
            report.json
